import Foundation
import ArgumentParser
import LDACore

struct Setup: ParsableCommand {
    static let configuration = CommandConfiguration(abstract: "Install an exported LDA AI-client setup, preserving existing settings.")
    @Option(help: "Local setup payload generated by LDA Settings.")
    var payloadBase64: String

    func run() throws {
        let override = ProcessInfo.processInfo.environment["CODEX_HOME"].flatMap { $0.isEmpty ? nil : URL(fileURLWithPath: $0) }
        print(try AIClientInstaller.install(payloadBase64: payloadBase64, codexHome: override))
    }
}
