//
//  EncryptedContainerTests.swift
//  LDACoreTests
//
//  The shared encrypted container: round trips, tamper detection, wrong
//  passphrase, and MappingStore on-disk compatibility across the refactor.
//
//  House rules: all comments and strings in English. No em-dash and no
//  en-dash-as-separator anywhere.
//

import XCTest
@testable import LDACore

final class EncryptedContainerTests: XCTestCase {

    private let container = EncryptedContainer(
        magic: Array("LDATEST".utf8),
        keychainService: "ai.openclaw.lda.testkey",
        containerDescription: "Test container"
    )

    // MARK: - Hermetic working directory

    private var workDir: URL!

    override func setUpWithError() throws {
        try super.setUpWithError()
        workDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("EncryptedContainerTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(
            at: workDir,
            withIntermediateDirectories: true
        )
    }

    override func tearDownWithError() throws {
        if let workDir, FileManager.default.fileExists(atPath: workDir.path) {
            try? FileManager.default.removeItem(at: workDir)
        }
        workDir = nil
        try super.tearDownWithError()
    }

    private func tempURL(_ ext: String) -> URL {
        workDir
            .appendingPathComponent(UUID().uuidString)
            .appendingPathExtension(ext)
    }

    func testPassphraseRoundTrip() throws {
        let url = tempURL("bin")
        let payload = Data("secret payload".utf8)
        try container.save(payload, to: url, protection: .passphrase("hunter2 long enough"))
        let back = try container.load(from: url, protection: .passphrase("hunter2 long enough"))
        XCTAssertEqual(back, payload)
    }

    func testWrongPassphraseFails() throws {
        let url = tempURL("bin")
        try container.save(Data("x".utf8), to: url, protection: .passphrase("right one"))
        XCTAssertThrowsError(
            try container.load(from: url, protection: .passphrase("wrong one"))
        ) { error in
            guard case DocumentIOError.decryptionFailed = error else {
                XCTFail("Expected decryptionFailed for wrong passphrase, got \(error)")
                return
            }
        }
    }

    func testTamperedContainerFails() throws {
        let url = tempURL("bin")
        try container.save(Data("payload".utf8), to: url, protection: .passphrase("p p p p"))
        var bytes = try Data(contentsOf: url)
        bytes[bytes.count - 1] ^= 0xFF
        try bytes.write(to: url)
        XCTAssertThrowsError(
            try container.load(from: url, protection: .passphrase("p p p p"))
        ) { error in
            guard case DocumentIOError.decryptionFailed = error else {
                XCTFail("Expected decryptionFailed for tampered container, got \(error)")
                return
            }
        }
    }

    func testWrongMagicRejected() throws {
        let url = tempURL("bin")
        try container.save(Data("payload".utf8), to: url, protection: .passphrase("p p p p"))
        let other = EncryptedContainer(
            magic: Array("LDAOTHER".utf8),
            keychainService: "ai.openclaw.lda.testkey",
            containerDescription: "Other container"
        )
        XCTAssertThrowsError(
            try other.load(from: url, protection: .passphrase("p p p p"))
        ) { error in
            guard case DocumentIOError.corrupt = error else {
                XCTFail("Expected corrupt for wrong magic, got \(error)")
                return
            }
        }
    }

    /// The refactor must not change MappingStore's on-disk format. A container
    /// saved with MappingStore BEFORE this refactor (fixture bytes inlined
    /// below, generated at Step 2.2) must still load AFTER.
    func testMappingStorePreRefactorFixtureStillLoads() throws {
        // Generated by FixtureGenerator.testPrintPreRefactorFixtureBase64 on
        // 2026-06-10 against the pre-refactor build (commit d413428).
        let base64 = "TERBTUFQAQEQOEM8c5Sz/YXBGrqtN6EOQT3I5iXq5cBBkUEjIrXriLxYXSaXvOoOPPjhb/aMSwfYK6kkNxqZyN9thCKqJFssJZnC9f58KArtrKrd0tfs20oV7th7o04scOdYeqXY/lGvlXvvWmQtjdeNYXMJLHw2E6x4YgdHuVAtKShdw+icgcrD3em72ulcupmOJSoKZv20Vdj0w30/7yPTHgadcjfozKqJj/urEt2tDucTwKKfSouoZH/crEEk4pA1sTrvLQMtSk9Kn3hkB7Qy3klx6TdJkSAUUvTee2tZ89eLFyQSThjDC9Uk/gQotUm7gx4="
        let url = tempURL("ldamap")
        guard let fixtureData = Data(base64Encoded: base64) else {
            XCTFail("Bad base64 in fixture")
            return
        }
        try fixtureData.write(to: url)
        let mapping = try MappingStore.load(from: url, protection: .passphrase("fixture pass"))
        XCTAssertEqual(mapping.entries["{PERSON_1}"]?.value, "Jane Roe")
    }
}
